name: "Validate Gradle Wrapper"
on: [pull_request]

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Sample\ Code
    steps:
      - uses: actions/checkout@v3.0.0
      - uses: gradle/wrapper-validation-action@v1
